name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Étape 1: Récupération du code avec l'historique complet pour accéder aux tags
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Étape 2: Récupère le dernier tag Git si déclenchement manuel
      - name: Get latest tag
        id: get_tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.1")
          echo "TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Utilisation du tag: $LATEST_TAG"
      
      # Étape 3: Extrait les métadonnées pour Docker
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            dydhzo/fkstream
            ghcr.io/${{ github.repository }}
          tags: |
            # Pour les déclenchements par tag Git
            type=ref,event=tag
            # Pour le déclenchement manuel, utilise le dernier tag trouvé
            type=raw,value=${{ env.TAG }},enable=${{ github.event_name == 'workflow_dispatch' }}
            # Toujours ajouter le tag latest
            type=raw,value=latest
      
      # Étape 4: Configuration de QEMU pour l'émulation des architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      
      # Étape 5: Configuration de Docker Buildx pour le build multi-architecture
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
          platforms: linux/amd64,linux/arm64
      
      # Étape 6: Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Étape 7: Connexion à GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Étape 8: Construction et publication de l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Améliore la stabilité du build multi-architecture
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
