name: Docker Image CI

on:
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    # Étape 1: Récupération du code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Étape 2: Extrait les métadonnées
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          dydhzo/fkstream
          ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}

    # Étape 3: Met en place Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Étape 4: Connexion à Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Étape 5: Connexion à GitHub Container Registry (GHCR.io)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Étape 6: Construit l'image Docker et la pousse sur les deux
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
