name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    # Étape 1: Récup du code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Étape 2: Mise en place Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Étape 3: Vers docker hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Étape 4: Connexion à GitHub Container Registry (GHCR.io)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Étape 5: Construit l'image Docker et la pousse sur les deux
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          dydhzo/fkstream:latest
          ghcr.io/${{ github.repository_owner }}/fkstream:latest
